name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Cargo test
        working-directory: ./mips-emulator
        run: cargo test
      
      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Run wasm-pack build
        working-directory: ./mips-emulator
        run: wasm-pack build

      - name: install
        working-directory: ./app
        run: npm i --legacy-peer-deps

      - name: build
        working-directory: ./app
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './app/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
